<template>
    <svg width="400"
         height="240"
         viewBox="0 0 400 240"
         fill="none"
         xmlns="http://www.w3.org/2000/svg">
        <defs>
            <pattern id="a"
                     x="0"
                     y="0"
                     width="20"
                     height="20"
                     patternUnits="userSpaceOnUse">
                <circle cx="1"
                        cy="1"
                        r="1"
                        fill="var(--border-neutral-regular-default)" />
            </pattern>
        </defs>
        <path fill="url(#a)"
              d="M0 0h400v240H0z" />
        <g stroke="var(--border-neutral-regular-default)"
           stroke-dasharray="4 4">
            <path d="M100 10v220M300 10v220" />
            <path d="M10 32h380M10 208h380" />
        </g>
        <g transform="translate(100 32)">
            <rect width="200"
                  height="176"
                  rx="8"
                  fill="var(--background-neutral-strong-default)"
                  stroke="var(--border-neutral-strong-default)"
                  stroke-width="2" />
            <path d="M0 40h200M0 64h200"
                  stroke="var(--border-neutral-regular-default)" />
            <g transform="translate(12 12)">
                <rect width="64"
                      height="14"
                      rx="4"
                      fill="var(--background-neutral-regular-default)" />
                <g transform="translate(144)"
                   stroke="var(--border-neutral-regular-default)"
                   stroke-width="1.5">
                    <rect width="14"
                          height="14"
                          rx="4" />
                    <rect x="22"
                          width="14"
                          height="14"
                          rx="4" />
                </g>
            </g>
            <g transform="translate(12 48)"
               fill="var(--background-neutral-regular-default)">
                <rect width="16"
                      height="8"
                      rx="2" />
                <rect x="26"
                      width="16"
                      height="8"
                      rx="2" />
                <rect x="52"
                      width="16"
                      height="8"
                      rx="2" />
                <rect x="78"
                      width="16"
                      height="8"
                      rx="2" />
                <rect x="104"
                      width="16"
                      height="8"
                      rx="2" />
                <rect x="130"
                      width="16"
                      height="8"
                      rx="2" />
                <rect x="156"
                      width="16"
                      height="8"
                      rx="2" />
            </g>
            <g transform="translate(12 76)">
                <rect x="52"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="78"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="104"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="130"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="156"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect y="27"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="26"
                      y="27"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="52"
                      y="27"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--alpha-white-10)"
                      stroke="var(--content-primary-regular-default)"
                      stroke-width="1.5"
                      stroke-dasharray="2 2"
                      class="blink-blue" />
                <rect x="78"
                      y="27"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="104"
                      y="27"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="130"
                      y="27"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="156"
                      y="27"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect y="54"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="26"
                      y="54"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="52"
                      y="54"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="78"
                      y="54"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="104"
                      y="54"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="130"
                      y="54"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
                <rect x="156"
                      y="54"
                      width="22"
                      height="22"
                      rx="4"
                      fill="var(--background-neutral-regular-default)"
                      stroke="var(--border-neutral-regular-default)" />
            </g>
        </g>
    </svg>
</template>
