<template>
    <svg width="400"
         height="240"
         viewBox="0 0 400 240"
         fill="none"
         xmlns="http://www.w3.org/2000/svg">
        <defs>
            <pattern id="a"
                     x="0"
                     y="0"
                     width="20"
                     height="20"
                     patternUnits="userSpaceOnUse">
                <circle cx="1"
                        cy="1"
                        r="1"
                        fill="var(--border-neutral-regular-default)" />
            </pattern>
        </defs>
        <path fill="url(#a)"
              d="M0 0h400v240H0z" />
        <path d="M135 10v220M265 10v220M10 120h380"
              stroke="var(--border-neutral-regular-default)"
              stroke-dasharray="4 4" />
        <g transform="translate(20 25)">
            <rect width="100"
                  height="80"
                  rx="6"
                  fill="var(--background-neutral-strong-default)"
                  stroke="var(--border-neutral-strong-default)"
                  stroke-width="2" />
            <rect x="12"
                  y="12"
                  width="24"
                  height="24"
                  rx="4"
                  fill="var(--border-neutral-light-default)" />
            <rect x="12"
                  y="48"
                  width="76"
                  height="6"
                  rx="3"
                  fill="var(--border-neutral-light-default)" />
            <rect x="12"
                  y="60"
                  width="40"
                  height="6"
                  rx="3"
                  fill="var(--border-neutral-light-default)" />
            <g transform="translate(130)">
                <rect width="100"
                      height="80"
                      rx="6"
                      fill="var(--background-neutral-strong-default)"
                      stroke="var(--border-neutral-strong-default)"
                      stroke-width="2" />
                <rect x="12"
                      y="12"
                      width="24"
                      height="24"
                      rx="4"
                      fill="var(--border-neutral-light-default)" />
                <rect x="12"
                      y="48"
                      width="76"
                      height="6"
                      rx="3"
                      fill="var(--border-neutral-light-default)" />
                <rect x="12"
                      y="60"
                      width="40"
                      height="6"
                      rx="3"
                      fill="var(--border-neutral-light-default)" />
            </g>
            <g transform="translate(260)">
                <rect width="100"
                      height="80"
                      rx="6"
                      fill="var(--background-neutral-strong-default)"
                      stroke="var(--border-neutral-strong-default)"
                      stroke-width="2" />
                <rect x="12"
                      y="12"
                      width="24"
                      height="24"
                      rx="4"
                      fill="var(--border-neutral-light-default)" />
                <rect x="12"
                      y="48"
                      width="76"
                      height="6"
                      rx="3"
                      fill="var(--border-neutral-light-default)" />
                <rect x="12"
                      y="60"
                      width="40"
                      height="6"
                      rx="3"
                      fill="var(--border-neutral-light-default)" />
            </g>
        </g>
        <g transform="translate(20 135)">
            <rect width="100"
                  height="80"
                  rx="6"
                  fill="var(--background-neutral-strong-default)"
                  stroke="var(--border-neutral-strong-default)"
                  stroke-width="2" />
            <rect x="12"
                  y="12"
                  width="24"
                  height="24"
                  rx="4"
                  fill="var(--border-neutral-light-default)" />
            <rect x="12"
                  y="48"
                  width="76"
                  height="6"
                  rx="3"
                  fill="var(--border-neutral-light-default)" />
            <rect x="12"
                  y="60"
                  width="40"
                  height="6"
                  rx="3"
                  fill="var(--border-neutral-light-default)" />
            <g transform="translate(130)">
                <rect width="100"
                      height="80"
                      rx="6"
                      fill="var(--background-neutral-strong-default)"
                      stroke="var(--border-neutral-strong-default)"
                      stroke-width="2" />
                <rect x="12"
                      y="12"
                      width="24"
                      height="24"
                      rx="4"
                      fill="var(--border-neutral-light-default)" />
                <rect x="12"
                      y="48"
                      width="76"
                      height="6"
                      rx="3"
                      fill="var(--border-neutral-light-default)" />
                <rect x="12"
                      y="60"
                      width="40"
                      height="6"
                      rx="3"
                      fill="var(--border-neutral-light-default)" />
            </g>
            <g transform="translate(260)">
                <rect width="100"
                      height="80"
                      rx="6"
                      fill="var(--background-neutral-strong-default)"
                      stroke="var(--border-neutral-strong-default)"
                      stroke-width="2" />
                <rect x="12"
                      y="12"
                      width="24"
                      height="24"
                      rx="4"
                      fill="var(--border-neutral-light-default)" />
                <rect x="12"
                      y="48"
                      width="76"
                      height="6"
                      rx="3"
                      fill="var(--border-neutral-light-default)" />
                <rect x="12"
                      y="60"
                      width="40"
                      height="6"
                      rx="3"
                      fill="var(--border-neutral-light-default)" />
            </g>
        </g>
    </svg>
</template>
